using System.Text.RegularExpressions;
using DosBoxSelector.Models;

namespace DosBoxSelector.Services;

/// <summary>
/// Finds <c>.conf</c> files in the target folder and works out which flavor each was written for.
/// </summary>
public static partial class ConfScanner
{
    /// <summary>
    /// How much of the file to read. The generator header is on line 1, but DOSBox-X opens with
    /// roughly 4 KB of comments before its first setting, so the window has to be comfortably
    /// larger than that for the headerless fallback to see anything.
    /// </summary>
    private const int SniffBytes = 32768;

    public static List<ConfMatch> Scan(string directory, IReadOnlyList<DosBoxFlavor> flavors)
    {
        List<string> files;
        try
        {
            files = Directory.EnumerateFiles(directory, "*.conf", SearchOption.TopDirectoryOnly)
                .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return [];
        }

        var results = new List<ConfMatch>(files.Count);
        foreach (var path in files)
        {
            var name = Path.GetFileName(path);

            // Content wins over filename: a file called dosbox.conf may well have been
            // generated by DOSBox-X, and its own header says so.
            var byContent = MatchByContent(path, flavors);
            if (byContent is not null)
            {
                results.Add(new ConfMatch(path, name, byContent, ConfMatchSource.Content));
                continue;
            }

            var byName = MatchByFileName(name, flavors);
            results.Add(byName is not null
                ? new ConfMatch(path, name, byName, ConfMatchSource.FileName)
                : new ConfMatch(path, name, null, ConfMatchSource.None));
        }

        return results;
    }

    /// <summary>
    /// Reads the head of the file looking for a self-identifying marker.
    ///
    /// All three flavors open a generated config with a line naming themselves, and the exact
    /// wording differs per fork:
    /// <code>
    /// # This is the configuration file for DOSBox-X 2026.08.02. ...
    /// # This is the configuration file for DOSBox Staging (0.82.2).
    /// # This is the configuration file for DOSBox 0.74-3. ...
    /// </code>
    /// That header is checked first and is authoritative. Only a file without one falls back to
    /// looking for settings unique to a fork.
    /// </summary>
    private static string? MatchByContent(string path, IReadOnlyList<DosBoxFlavor> flavors)
    {
        string head;
        try
        {
            using var stream = File.OpenRead(path);
            var buffer = new byte[SniffBytes];
            var read = stream.Read(buffer, 0, buffer.Length);
            head = System.Text.Encoding.UTF8.GetString(buffer, 0, read);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return null;
        }

        // The header wins outright. It must be tested before any settings heuristic: a genuine
        // Staging config contains settings that also exist in DOSBox-X, so leading with the
        // heuristic misfiles it.
        var header = GeneratorHeader().Match(head);
        if (header.Success)
        {
            // Group order in the pattern is significant — "DOSBox-X" and "DOSBox Staging" both
            // contain "DOSBox", so the bare name is only reached when neither matched.
            if (header.Groups["x"].Success)
                return FindFlavor(flavors, "dosbox-x", "DOSBox-X");
            if (header.Groups["staging"].Success)
                return FindFlavor(flavors, "dosbox-staging", "DOSBox Staging");
            if (header.Groups["vanilla"].Success)
                return FindFlavor(flavors, "dosbox-vanilla", "DOSBox");
        }

        // No header — fall back to settings that exist in DOSBox-X and in neither of the others.
        if (DosBoxXOnlySetting().IsMatch(head))
            return FindFlavor(flavors, "dosbox-x", "DOSBox-X");

        return null;
    }

    /// <summary>The self-identifying comment each fork writes at the top of a generated config.</summary>
    [GeneratedRegex(
        @"configuration\s*file\s*for\s*(?:(?<x>DOSBox-X)|(?<staging>DOSBox[ -]Staging)|(?<vanilla>DOSBox))\b",
        RegexOptions.IgnoreCase)]
    private static partial Regex GeneratorHeader();

    /// <summary>
    /// Settings that appear in a DOSBox-X config and in neither DOSBox Staging's nor vanilla
    /// DOSBox's, verified against configs generated by all three. Note <c>vmemsize</c> is
    /// deliberately absent — Staging has it too — while <c>vmemsizekb</c> is DOSBox-X's alone.
    /// </summary>
    [GeneratedRegex(
        @"^\s*(isapnpbios|apmbios|pnp|a20|voodoo_card|voodoo_maxmem|vmemsizekb|fastbioslogo|shellhide)\s*=",
        RegexOptions.IgnoreCase | RegexOptions.Multiline)]
    private static partial Regex DosBoxXOnlySetting();

    /// <summary>
    /// Resolves a well-known flavor by its seeded id, falling back to display name so the match
    /// still works if the user renamed or recreated the entry.
    /// </summary>
    private static string? FindFlavor(IReadOnlyList<DosBoxFlavor> flavors, string id, string displayName)
    {
        var byId = flavors.FirstOrDefault(f => f.Id == id);
        if (byId is not null)
            return byId.Id;

        var byName = flavors.FirstOrDefault(
            f => string.Equals(f.DisplayName, displayName, StringComparison.OrdinalIgnoreCase));
        return byName?.Id;
    }

    private static string? MatchByFileName(string fileName, IReadOnlyList<DosBoxFlavor> flavors)
    {
        // Patterns are ordered most-specific-first within a flavor, but flavors themselves can
        // overlap (both vanilla and Staging list dosbox.conf). Prefer a flavor whose *first*
        // pattern matches, so dosbox-staging.conf beats a generic dosbox.conf claim.
        foreach (var exactFirst in new[] { true, false })
        {
            foreach (var flavor in flavors)
            {
                for (var i = 0; i < flavor.ConfPatterns.Count; i++)
                {
                    if (exactFirst && i != 0)
                        continue;

                    if (GlobMatches(flavor.ConfPatterns[i], fileName))
                        return flavor.Id;
                }
            }
        }

        return null;
    }

    private static bool GlobMatches(string pattern, string fileName)
    {
        if (string.IsNullOrWhiteSpace(pattern))
            return false;

        var regex = "^" + Regex.Escape(pattern).Replace("\\*", ".*").Replace("\\?", ".") + "$";
        return Regex.IsMatch(fileName, regex, RegexOptions.IgnoreCase);
    }
}
